# Generated by Django 5.0.7 on 2024-08-01 10:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="user__username"
            ),
        ),
    ]
